[env]
TERM = "xterm-256color"

[scrolling]
history = 65535

[window]
padding = { x = 2, y = 2 }

[font]
size = 10.4
normal = { family = "CommitMonoNerdFont", style = "Bold" }
bold = { family = "CommitMonoNerdFont", style = "Bold" }
italic = { family = "CommitMonoNerdFont", style = "Italic" }
bold_italic = { family = "CommitMonoNerdFont", style = "Bold Italic" }

# Tango Dark
[colors.bright]
black = "#555753"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#3465a4"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#c4a000"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.selection]
background = "#b5d5ff"
text = "#000000"

[selection]
save_to_clipboard = true

# Block cursor with no blinking
[cursor.style]
shape = "block"
blinking = "Off"
